# Generated by Django 3.1.6 on 2021-02-09 08:01

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path


DATA_FILENAME = 'data.json'


def load_data(apps, schema_editor):
    Station = apps.get_model('stations', 'Station')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME  # path to the data.json file

    with open(str(jsonfile), encoding='mbcs') as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name', 'no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    city = obj.get('addr:city', '')
                    address = obj.get('addr:street', '')
                    location = fromstr("POINT({} {})".format(longitude, latitude), srid=4326)
                    # The 4326 srid (Spatial Reference System Identifier) is the most popular system used with PostGIS
                    Station(name=name, location=location, address=address, city=city).save()
            except KeyError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
